# Generated by Django 4.2 on 2023-04-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mahsulot_sotuvchi'),
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savat',
            name='mahsulot',
        ),
        migrations.RemoveField(
            model_name='savat',
            name='miqdor',
        ),
        migrations.RemoveField(
            model_name='savat',
            name='yetkazish',
        ),
        migrations.AddField(
            model_name='savat',
            name='sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='SavatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('yetkazish', models.PositiveSmallIntegerField(default=4)),
                ('umumiy_summa', models.IntegerField(blank=True, null=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot')),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma.savat')),
            ],
        ),
    ]
